name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
#     - name: Run ESLint
#       run: eslint . --ext .js,.jsx,.ts,.tsx
    - name: Lint Action
      uses: wearerequired/lint-action@v1.6.0

